version: "3.8"

services:
  api: # <---- Este é o nome do serviço
    image: genesisbrito/backend-automatico:latest
    env_file:
      - .env
    networks:
      - PolariumNet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        # --- Configuração do Traefik ---
        - "traefik.enable=true"
        - "traefik.docker.network=PolariumNet"

        # --- Roteador HTTP (Corrigido) ---
        - "traefik.http.routers.api-http.rule=Host(`backend-automatico.tipolariumbroker.com`)"
        - "traefik.http.routers.api-http.entrypoints=web"
        - "traefik.http.routers.api-http.middlewares=redirect-to-https"

        # --- Middleware de Redirecionamento (não precisa de alteração) ---
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

        # --- Roteador HTTPS (Corrigido) ---
        - "traefik.http.routers.api-https.rule=Host(`backend-automatico.tipolariumbroker.com`)"
        - "traefik.http.routers.api-https.entrypoints=websecure"
        - "traefik.http.routers.api-https.tls.certresolver=letsencryptresolver"

        # --- Serviço (Corrigido) ---
        - "traefik.http.services.api.loadbalancer.server.port=2003" # O nome do serviço aqui DEVE ser 'api'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  PolariumNet:
    external: true