version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      
      - "3001:3001"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

